pipeline {
    agent any
    
    stages {
        stage ('Compile stage')
        {
            steps {
            withMaven(maven : 'maven_3_4_5')
            {
            sh 'mvn clean compile'
                
            }
        }
    }
    
    stage ('Testing Stage')
    {
        steps {
            withMaven(maven : 'maven_3_4_5')
            {
            sh 'mvn test'
            }
        }
    }
    
     stage ('Testing Stage')
    {
        steps {
            withMaven(maven : 'maven_3_4_5')
            {
            sh 'mvn deploy'
            }
        }
    }
    
  }
    
}
